CREATE DATABASE QL_GiangDay;
USE QL_GiangDay;

-- 1. Bảng Tài khoản
CREATE TABLE TaiKhoan (
    TenDangNhap VARCHAR(255) PRIMARY KEY,
    MatKhau VARCHAR(255) NOT NULL,
    LoaiTaiKhoan NVARCHAR(50) NOT NULL -- Admin, GiangVien, SinhVien
);
GO

-- 2. Bảng Khoa
CREATE TABLE Khoa (
    MaKhoa VARCHAR(50) PRIMARY KEY,
    TenKhoa NVARCHAR(255) NOT NULL
);
GO

-- 3. Bảng Học kỳ
CREATE TABLE HocKy (
    MaHocKy VARCHAR(50) PRIMARY KEY,  -- ví dụ: 2025HK1
    TenHocKy NVARCHAR(255) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL
);
GO

-- 4. Bảng Giảng viên
CREATE TABLE GiangVien (
    MaGV VARCHAR(50) PRIMARY KEY,
    TenGV NVARCHAR(255) NOT NULL,
    HocVi NVARCHAR(100),
    MaKhoa VARCHAR(50) NOT NULL,
    TenDangNhap VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
    FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan(TenDangNhap)
);
GO

-- 5. Bảng Môn học
CREATE TABLE MonHoc (
    MaMH VARCHAR(50) PRIMARY KEY,
    TenMH NVARCHAR(255) NOT NULL,
    SoTC INT NOT NULL,
    TietLT INT NOT NULL,
    TietTH INT NOT NULL,
    HeSoDiem NVARCHAR(10),               -- Ví dụ: '4/6', '5/5'
    MaKhoa VARCHAR(50) NOT NULL,
    FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);
GO

-- 6. Bảng Sinh viên
CREATE TABLE SinhVien (
    MaSV VARCHAR(50) PRIMARY KEY,
    TenSV NVARCHAR(255) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10),
    QueQuan NVARCHAR(255),
    NgayNhapHoc DATE NOT NULL,
    MaKhoa VARCHAR(50) NOT NULL,
    TenDangNhap VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
    FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan(TenDangNhap)
);
GO

-- 7. Bảng Admin
CREATE TABLE Admin (
    MaAdmin VARCHAR(50) PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    TenDangNhap VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan(TenDangNhap)
);
GO

-- 8. Bảng Lớp tín chỉ
CREATE TABLE LopTC (
    MaLTC VARCHAR(50) PRIMARY KEY,
    TenLTC NVARCHAR(255) NOT NULL,
    MaMH VARCHAR(50) NOT NULL,
    MaGV VARCHAR(50) NOT NULL,
    MaHocKy VARCHAR(50) NOT NULL,
    NamHoc VARCHAR(10) NOT NULL,             -- ví dụ: '2024-2025'
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH),
    FOREIGN KEY (MaGV) REFERENCES GiangVien(MaGV),
    FOREIGN KEY (MaHocKy) REFERENCES HocKy(MaHocKy)
);
GO

-- 9. Bảng Sinh viên - Lớp tín chỉ
CREATE TABLE SinhVien_LopTC (
    MaSV VARCHAR(50) NOT NULL,
    MaLTC VARCHAR(50) NOT NULL,
    PRIMARY KEY (MaSV, MaLTC),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaLTC) REFERENCES LopTC(MaLTC)
);
GO

-- 10. Bảng Lịch học
CREATE TABLE LichHoc (
    MaLich VARCHAR(50) PRIMARY KEY,
    MaLTC VARCHAR(50) NOT NULL,
    PhongHoc NVARCHAR(100),
    Thu INT CHECK (Thu BETWEEN 2 AND 8),
    TietHoc INT,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    FOREIGN KEY (MaLTC) REFERENCES LopTC(MaLTC)
);
GO

-- 11. Bảng Phân công giảng dạy
CREATE TABLE PhanCong (
    MaPC VARCHAR(50) PRIMARY KEY,
    NgayPC DATE NOT NULL,
    KhuVuc NVARCHAR(50),
    TuGio DATETIME NOT NULL,
    DenGio DATETIME NOT NULL,
    NamHoc VARCHAR(10) NOT NULL,
    MaHocKy VARCHAR(50) NOT NULL,
    PhongHoc NVARCHAR(100),
    MaGV VARCHAR(50) NOT NULL,
    MaMH VARCHAR(50) NOT NULL,
    MaLTC VARCHAR(50) NOT NULL,
    FOREIGN KEY (MaGV) REFERENCES GiangVien(MaGV),
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH),
    FOREIGN KEY (MaLTC) REFERENCES LopTC(MaLTC),
    FOREIGN KEY (MaHocKy) REFERENCES HocKy(MaHocKy)
);
GO

-- 12. Bảng Yêu cầu đổi lịch học
CREATE TABLE YeuCauLichHoc (
    MaYeuCau VARCHAR(50) PRIMARY KEY,
    MaGV VARCHAR(50) NOT NULL,
    MaLich VARCHAR(50) NOT NULL,
    NoiDung NVARCHAR(500) NOT NULL,
    TrangThai NVARCHAR(50) DEFAULT N'Chờ duyệt'
        CHECK (TrangThai IN (N'Chờ duyệt', N'Đã duyệt', N'Từ chối')),
    NgayGui DATE DEFAULT GETDATE(),
    FOREIGN KEY (MaGV) REFERENCES GiangVien(MaGV),
    FOREIGN KEY (MaLich) REFERENCES LichHoc(MaLich)
);
GO

-- 13. Bảng Điểm
CREATE TABLE Diem (
    MaDiem VARCHAR(50) PRIMARY KEY,
    MaSV VARCHAR(50) NOT NULL,
    MaLTC VARCHAR(50) NOT NULL,
    PhanTramTrenLop FLOAT CHECK (PhanTramTrenLop BETWEEN 0 AND 100),
    PhanTramThi FLOAT CHECK (PhanTramThi BETWEEN 0 AND 100),
    DiemTrenLop FLOAT CHECK (DiemTrenLop BETWEEN 0 AND 10),
    DiemThi FLOAT CHECK (DiemThi BETWEEN 0 AND 10),
    DiemTB FLOAT CHECK (DiemTB BETWEEN 0 AND 10),
    DiemTB4 FLOAT CHECK (DiemTB4 BETWEEN 0 AND 4),
    Loai CHAR(1) CHECK (Loai IN ('A','B','C','D','F')),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaLTC) REFERENCES LopTC(MaLTC)
);
GO

-- 14. Bảng Điểm danh
CREATE TABLE DiemDanh (
    MaDiemDanh VARCHAR(50) PRIMARY KEY,
    MaSV VARCHAR(50) NOT NULL,
    MaLich VARCHAR(50) NOT NULL,
    Ngay DATE NOT NULL,
    TrangThai NVARCHAR(20) NOT NULL      
        CHECK (TrangThai IN (N'Có mặt', N'Vắng', N'Muộn')),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaLich) REFERENCES LichHoc(MaLich)
);
GO

-- 15. Bảng Đánh giá sinh viên
CREATE TABLE DanhGia (
    MaDanhGia VARCHAR(50) PRIMARY KEY,
    MaSV VARCHAR(50) NOT NULL,
    MaGV VARCHAR(50) NOT NULL,
    MaMH VARCHAR(50) NOT NULL,
    NhanXet NVARCHAR(500),
    NgayDanhGia DATE DEFAULT GETDATE(),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY (MaGV) REFERENCES GiangVien(MaGV),
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
);
GO
